employees=[{"eid":1,"ename":"Cathi","gender":"Female","country":"China"},
{"eid":2,"ename":"Powell","gender":"Male","country":"France"},
{"eid":3,"ename":"Kenyon","gender":"Male","country":"China"},
{"eid":4,"ename":"Alaster","gender":"Male","country":"Haiti"},
{"eid":5,"ename":"Ahmed","gender":"Male","country":"China"},
{"eid":6,"ename":"Shayne","gender":"Male","country":"Indonesia"},
{"eid":7,"ename":"Emelina","gender":"Female","country":"China"},
{"eid":8,"ename":"Rosemaria","gender":"Genderfluid","country":"Nigeria"},
{"eid":9,"ename":"Marcile","gender":"Female","country":"Indonesia"},
{"eid":10,"ename":"Felecia","gender":"Female","country":"China"},
{"eid":11,"ename":"Giulietta","gender":"Genderfluid","country":"Sweden"},
{"eid":12,"ename":"Krissy","gender":"Female","country":"Russia"},
{"eid":13,"ename":"Kermy","gender":"Male","country":"France"},
{"eid":14,"ename":"Hortense","gender":"Female","country":"China"},
{"eid":15,"ename":"Caleb","gender":"Male","country":"China"},
{"eid":16,"ename":"Randal","gender":"Male","country":"North Korea"},
{"eid":17,"ename":"Arturo","gender":"Male","country":"Argentina"},
{"eid":18,"ename":"Freedman","gender":"Male","country":"China"},
{"eid":19,"ename":"Isaac","gender":"Male","country":"Sweden"},
{"eid":20,"ename":"Caresa","gender":"Female","country":"Mexico"},
{"eid":21,"ename":"Burg","gender":"Male","country":"Vietnam"},
{"eid":22,"ename":"Deerdre","gender":"Female","country":"Brazil"},
{"eid":23,"ename":"Wynne","gender":"Female","country":"China"},
{"eid":24,"ename":"Amos","gender":"Male","country":"China"},
{"eid":25,"ename":"Erma","gender":"Female","country":"China"},
{"eid":26,"ename":"Charita","gender":"Female","country":"Slovenia"},
{"eid":27,"ename":"Cybill","gender":"Agender","country":"Ecuador"},
{"eid":28,"ename":"Lanae","gender":"Female","country":"Poland"},
{"eid":29,"ename":"Gil","gender":"Male","country":"China"},
{"eid":30,"ename":"Elbertina","gender":"Female","country":"China"},
{"eid":31,"ename":"Rodger","gender":"Male","country":"Portugal"},
{"eid":32,"ename":"Horace","gender":"Male","country":"South Africa"},
{"eid":33,"ename":"Tyrus","gender":"Male","country":"Czech Republic"},
{"eid":34,"ename":"Hort","gender":"Male","country":"Bangladesh"},
{"eid":35,"ename":"Stella","gender":"Female","country":"China"},
{"eid":36,"ename":"Dun","gender":"Male","country":"Indonesia"},
{"eid":37,"ename":"Omero","gender":"Male","country":"Colombia"},
{"eid":38,"ename":"Shayla","gender":"Female","country":"China"},
{"eid":39,"ename":"Geoffrey","gender":"Genderfluid","country":"China"},
{"eid":40,"ename":"Hastie","gender":"Male","country":"Greece"},
{"eid":41,"ename":"Clayborn","gender":"Male","country":"Poland"},
{"eid":42,"ename":"George","gender":"Female","country":"China"},
{"eid":43,"ename":"Sigfried","gender":"Male","country":"Czech Republic"},
{"eid":44,"ename":"Lenore","gender":"Polygender","country":"United Kingdom"},
{"eid":45,"ename":"Wendy","gender":"Female","country":"Uganda"},
{"eid":46,"ename":"Davine","gender":"Female","country":"Brazil"},
{"eid":47,"ename":"Anette","gender":"Female","country":"Pakistan"},
{"eid":48,"ename":"Umeko","gender":"Female","country":"Kuwait"},
{"eid":49,"ename":"Richy","gender":"Male","country":"Thailand"},
{"eid":50,"ename":"Brooke","gender":"Male","country":"Philippines"},
{"eid":51,"ename":"Leonhard","gender":"Male","country":"China"},
{"eid":52,"ename":"Elianore","gender":"Female","country":"Philippines"},
{"eid":53,"ename":"Dru","gender":"Female","country":"Mexico"},
{"eid":54,"ename":"Daffi","gender":"Female","country":"Spain"},
{"eid":55,"ename":"Gan","gender":"Male","country":"China"},
{"eid":56,"ename":"Alard","gender":"Male","country":"Philippines"},
{"eid":57,"ename":"Toma","gender":"Female","country":"Sweden"},
{"eid":58,"ename":"Taylor","gender":"Male","country":"Japan"},
{"eid":59,"ename":"Lucky","gender":"Female","country":"Colombia"},
{"eid":60,"ename":"Sibyl","gender":"Female","country":"United Kingdom"},
{"eid":61,"ename":"Bradford","gender":"Genderfluid","country":"Netherlands"},
{"eid":62,"ename":"Alphonso","gender":"Male","country":"Equatorial Guinea"},
{"eid":63,"ename":"Casar","gender":"Male","country":"Russia"},
{"eid":64,"ename":"Marcelia","gender":"Female","country":"Poland"},
{"eid":65,"ename":"Franzen","gender":"Male","country":"Brazil"},
{"eid":66,"ename":"Ansley","gender":"Female","country":"Indonesia"},
{"eid":67,"ename":"Kermie","gender":"Male","country":"Iran"},
{"eid":68,"ename":"Angus","gender":"Male","country":"Russia"},
{"eid":69,"ename":"Alayne","gender":"Female","country":"China"},
{"eid":70,"ename":"Taddeo","gender":"Male","country":"Russia"},
{"eid":71,"ename":"Roxana","gender":"Genderqueer","country":"Portugal"},
{"eid":72,"ename":"Meggy","gender":"Female","country":"China"},
{"eid":73,"ename":"Wendall","gender":"Male","country":"France"},
{"eid":74,"ename":"Correy","gender":"Male","country":"Nigeria"},
{"eid":75,"ename":"Philip","gender":"Male","country":"Colombia"},
{"eid":76,"ename":"Ursa","gender":"Female","country":"United Kingdom"},
{"eid":77,"ename":"Sandi","gender":"Female","country":"Mexico"},
{"eid":78,"ename":"Biddie","gender":"Female","country":"Tunisia"},
{"eid":79,"ename":"Addy","gender":"Female","country":"Philippines"},
{"eid":80,"ename":"Millard","gender":"Male","country":"Jamaica"},
{"eid":81,"ename":"Shadow","gender":"Male","country":"Indonesia"},
{"eid":82,"ename":"Anya","gender":"Female","country":"China"},
{"eid":83,"ename":"Juli","gender":"Female","country":"Poland"},
{"eid":84,"ename":"Florida","gender":"Female","country":"Sweden"},
{"eid":85,"ename":"Nickolai","gender":"Male","country":"Portugal"},
{"eid":86,"ename":"Starla","gender":"Female","country":"China"},
{"eid":87,"ename":"Roobbie","gender":"Female","country":"Philippines"},
{"eid":88,"ename":"Alard","gender":"Bigender","country":"Brazil"},
{"eid":89,"ename":"Cosette","gender":"Genderqueer","country":"Indonesia"},
{"eid":90,"ename":"Carie","gender":"Female","country":"China"},
{"eid":91,"ename":"Jeni","gender":"Female","country":"Niger"},
{"eid":92,"ename":"Jeannine","gender":"Female","country":"Austria"},
{"eid":93,"ename":"Faber","gender":"Male","country":"Venezuela"},
{"eid":94,"ename":"Demetris","gender":"Male","country":"Vietnam"},
{"eid":95,"ename":"Blaine","gender":"Male","country":"Thailand"},
{"eid":96,"ename":"Daphna","gender":"Female","country":"Tanzania"},
{"eid":97,"ename":"Fitzgerald","gender":"Non-binary","country":"Russia"},
{"eid":98,"ename":"Julian","gender":"Male","country":"China"},
{"eid":99,"ename":"Janek","gender":"Male","country":"United States"},
{"eid":100,"ename":"Maximilien","gender":"Male","country":"Afghanistan"}]

male_emp_names=[]
female_emp_names=[]

for emp in employees:
    if emp['gender']=='Male':
        male_emp_names.append(emp['ename'])

    elif emp['gender']=='Female':
        female_emp_names.append(emp['ename'])

print(len(male_emp_names))
print(len(female_emp_names))
